# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a73244ac1ad9bf48b91e15a827de2d435aeff59802967864aa08f2e610d5843433502e689423f0c6d46532dd3732f8a9bcdf10f1233c7c7e845f38c6ee10b553

test:
  secret_key_base: 473b1c32e95ef1fcb55da0780579cd1ee85ca27076fb9afe7ca6e97d2f346878378f613c34b8b9ad0dd0574ac76ed2ec55b6a9c1335f2d1081c2e1f689dbf0c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
